// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enrnwqmlbgenwhfnjden.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVucm53cW1sYmdlbndoZm5qZGVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDY4ODMsImV4cCI6MjA2NTQ4Mjg4M30.BKUEXUfudO00TQKIp1pGnyPTyijtgxkvlR-u55fAXMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);